apiVersion: apps/v1
kind: Deployment
metadata:
  name: hearloveen-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hearloveen-api
  template:
    metadata:
      labels:
        app: hearloveen-api
    spec:
      containers:
        - name: api
          image: my-api-image:latest
          ports:
            - containerPort: 8080