apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: {{ .Values.replicaCount }}
  selector: { matchLabels: { app: api } }
  template:
    metadata: { labels: { app: api } }
    spec:
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports: [{ containerPort: 8080 }]
        env:
        - name: ConnectionStrings__Postgres
          value: "{{ .Values.env.POSTGRES_CONN }}"
        - name: ConnectionStrings__ServiceBus
          value: "{{ .Values.env.SERVICEBUS_CONN }}"
        - name: ConnectionStrings__Redis
          value: "{{ .Values.env.REDIS_CONN }}"
        - name: Blob__AccountUrl
          value: "{{ .Values.env.BLOB_ACCOUNT_URL }}"
        - name: Blob__Container
          value: "{{ .Values.env.BLOB_CONTAINER }}"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector: { app: api }
  ports:
    - port: 80
      targetPort: 8080
